/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsCalculadora;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;

public class AppTest {

    Calculadora c;

    @Before
    public void setup() {
            c = new Calculadora();
    }

    @Test
    public void testSuma() {
        assertTrue(c.suma(2,3)==5);
    }

    @Test
    public void testResta() {
        assertTrue(c.resta(5,2)==3);
    }

    @Test
    public void testMultiplicacion() {
        assertTrue(c.multiplica(2,5)==10);
    }

    @Test
    public void testDivision() {
        assertTrue(c.divide(4,2)==2);
    }

}
