/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsCalculadora;

public class App {

    public static void main(String[] args) {
        Calculadora c = new Calculadora();

        System.out.println("Calculadora");
        System.out.println("===========");
    }

}
